### ISSUE TITLE
gradlew check is failing locally using mac os

### ISSUE THREAD

**Issue by laurentleseigneur** [avast/gradle-docker-compose-plugin#128]
when running `./gradlew check` localy on macos,  `com.avast.gradle.dockercompose.DockerComposePluginTest`is failling with exception

```
java.lang.RuntimeException: These ports of service web are declared as exposed but cannot be found in NetworkSettings: 80/tcp\n[Id:d3a13831066edae64b78c6ab9bbf4d15cba8525fdf466afbc7a5e07ac7757317, Created:2017-12-11T19:53:03.9426838Z, Path:nginx, Args:[-g, daemon off;], State:[Status:running, Running:true, Paused:false, Restarting:false, OOMKilled:false, Dead:false, Pid:20811, ExitCode:0, Error:, StartedAt:2017-12-11T19:53:04.4483571Z, FinishedAt:0001-01-01T00:00:00Z], Image:sha256:9e7424e5dbaeb9b28fea44d8c75b41ac6104989b49b2464b7cbbed16ceeccfc3, ResolvConfPath:/var/lib/docker/containers/d3a13831066edae64b78c6ab9bbf4d15cba8525fdf466afbc7a5e07ac7757317/resolv.conf, HostnamePath:/var/lib/docker/containers/d3a13831066edae64b78c6ab9bbf4d15cba8525fdf466afbc7a5e07ac7757317/hostname, HostsPath:/var/lib/docker/containers/d3a13831066edae64b78c6ab9bbf4d15cba8525fdf466afbc7a5e07ac7757317/hosts, LogPath:/var/lib/docker/containers/d3a13831066edae64b78c6ab9bbf4d15cba8525fdf466afbc7a5e07ac7757317/d3a13831066edae64b78c6ab9bbf4d15cba8525fdf466afbc7a5e07ac7757317-json.log, Name:/test_web_1, RestartCount:0, Driver:overlay2, Platform:linux, MountLabel:, ProcessLabel:, AppArmorProfile:, ExecIDs:null, HostConfig:[Binds:[], ContainerIDFile:, LogConfig:[Type:json-file, Config:[:]], NetworkMode:host, PortBindings:[80/tcp:[[HostIp:, HostPort:]]], RestartPolicy:[Name:, MaximumRetryCount:0], AutoRemove:false, VolumeDriver:, VolumesFrom:[], CapAdd:null, CapDrop:null, Dns:null, DnsOptions:null, DnsSearch:null, ExtraHosts:null, GroupAdd:null, IpcMode:shareable, Cgroup:, Links:null, OomScoreAdj:0, PidMode:, Privileged:false, PublishAllPorts:false, ReadonlyRootfs:false, SecurityOpt:null, UTSMode:, UsernsMode:, ShmSize:67108864, Runtime:runc, ConsoleSize:[0, 0], Isolation:, CpuShares:0, Memory:0, NanoCpus:0, CgroupParent:, BlkioWeight:0, BlkioWeightDevice:null, BlkioDeviceReadBps:null, BlkioDeviceWriteBps:null, BlkioDeviceReadIOps:null, BlkioDeviceWriteIOps:null, CpuPeriod:0, CpuQuota:0, CpuRealtimePeriod:0, CpuRealtimeRuntime:0, CpusetCpus:, CpusetMems:, Devices:null, DeviceCgroupRules:null, DiskQuota:0, KernelMemory:0, MemoryReservation:0, MemorySwap:0, MemorySwappiness:null, OomKillDisable:false, PidsLimit:0, Ulimits:null, CpuCount:0, CpuPercent:0, IOMaximumIOps:0, IOMaximumBandwidth:0], GraphDriver:[Data:[LowerDir:/var/lib/docker/overlay2/0eaca7e04fe7f01751c3c12c5d88e1d249be110e5d5c83e4eff405aae379df0b-init/diff:/var/lib/docker/overlay2/5c007f1f2f52254cb99ce2a0a5bd096fce57b30531e9389d1c26f418dde64faf/diff:/var/lib/docker/overlay2/da8b2e159d8f6edeabe13dba3d372bca873c2afa84369e1d3e82f8ac96fef296/diff:/var/lib/docker/overlay2/dd36f820b53ec7d399968e5119a12091a7b453490044b9b792b0d4e9e70aa74d/diff, MergedDir:/var/lib/docker/overlay2/0eaca7e04fe7f01751c3c12c5d88e1d249be110e5d5c83e4eff405aae379df0b/merged, UpperDir:/var/lib/docker/overlay2/0eaca7e04fe7f01751c3c12c5d88e1d249be110e5d5c83e4eff405aae379df0b/diff, WorkDir:/var/lib/docker/overlay2/0eaca7e04fe7f01751c3c12c5d88e1d249be110e5d5c83e4eff405aae379df0b/work], Name:overlay2], Mounts:[], Config:[Hostname:moby, Domainname:, User:, AttachStdin:false, AttachStdout:false, AttachStderr:false, ExposedPorts:[80/tcp:[:]], Tty:false, OpenStdin:false, StdinOnce:false, Env:[no_proxy=*.local, 169.254/16, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, NGINX_VERSION=1.13.7-1~stretch, NJS_VERSION=1.13.7.0.1.15-1~stretch], Cmd:[nginx, -g, daemon off;], ArgsEscaped:true, Image:nginx, Volumes:null, WorkingDir:, Entrypoint:null, OnBuild:null, Labels:[com.docker.compose.config-hash:77fdb8df7e17e5a50f6071cfc7e1decf6e77ea209492052e99e45efa3030396d, com.docker.compose.container-number:1, com.docker.compose.oneoff:False, com.docker.compose.project:test, com.docker.compose.service:web, com.docker.compose.version:1.16.1, maintainer:NGINX Docker Maintainers <docker-maint@nginx.com>], StopSignal:SIGTERM], NetworkSettings:[Bridge:, SandboxID:e3ebb297d8137c84e7951e73117e8ba99d0e94e7958ae8f1b3746e0817bb3ae1, HairpinMode:false, LinkLocalIPv6Address:, LinkLocalIPv6PrefixLen:0, Ports:[:], SandboxKey:/var/run/docker/netns/default, SecondaryIPAddresses:null, SecondaryIPv6Addresses:null, EndpointID:, Gateway:, GlobalIPv6Address:, GlobalIPv6PrefixLen:0, IPAddress:, IPPrefixLen:0, IPv6Gateway:, MacAddress:, Networks:[host:[IPAMConfig:null, Links:null, Aliases:null, NetworkID:493f03f8d0d41de68850c4dbe300bd164ce250eefa905bacc2120ab5ed582dc8, EndpointID:a0aa7e39bf7e57aa77e803d878c6a45e5e64d898a55b8b00bac5f0ba742e3404, Gateway:, IPAddress:, IPPrefixLen:0, IPv6Gateway:, GlobalIPv6Address:, GlobalIPv6PrefixLen:0, MacAddress:, DriverOpts:null]]]]
	at com.avast.gradle.dockercompose.DockerExecutor.validateDockerInspection(DockerExecutor.groovy:101)
	at com.avast.gradle.dockercompose.DockerExecutor.getValidDockerInspection(DockerExecutor.groovy:85)
	at com.avast.gradle.dockercompose.tasks.ComposeUp.createContainerInfos_closure5(ComposeUp.groovy:88)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at com.avast.gradle.dockercompose.tasks.ComposeUp.createContainerInfos(ComposeUp.groovy:86)
	at com.avast.gradle.dockercompose.tasks.ComposeUp.createServiceInfo(ComposeUp.groovy:81)
	at com.avast.gradle.dockercompose.tasks.ComposeUp.loadServicesInfo_closure4(ComposeUp.groovy:76)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at com.avast.gradle.dockercompose.tasks.ComposeUp.loadServicesInfo(ComposeUp.groovy:76)
	at com.avast.gradle.dockercompose.tasks.ComposeUp.up(ComposeUp.groovy:62)
	at com.avast.gradle.dockercompose.DockerComposePluginTest.expose localhost as a host for container with HOST networking(DockerComposePluginTest.groovy:189)
```

**Comment by augi** [comment]
The problem is that this test checks functionality with HOST networking that is working differently on Linux and MacOS. That's the reason why there is [this line of code](https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/test/groovy/com/avast/gradle/dockercompose/DockerComposePluginTest.groovy#L176) that should ensure this test is not executed on MacOS.

Could you please check what `System.properties['os.name']` is on your computer?

E.g. use this snippet in some `build.gradle`:
```gradle
task printOsName {
  doLast {
    println System.properties['os.name']
  }
}
```
`./gradlew printOsName`

Thanks!

**Comment by laurentleseigneur** [comment]
hi Augi,

on a Mac book pro with macOs High Sierra 10.13.1, result is `Mac OS X ` this mean your MacOs check `System.properties['os.name'].toString().toLowerCase().startsWith('macos') `fails since a i have a blank space between "Mac" and "OS"


```
╰─$ ./gradlew printOsName

> Task :printOsName
Mac OS X
```

**Comment by augi** [comment]
Thanks for the report, fixed.
