### ISSUE TITLE
MissingPropertyException: 'rootProject' is not property nor nested settings name

### ISSUE THREAD

**Issue by skissane** [avast/gradle-docker-compose-plugin#166]
Reproduce Steps:
1) Create a multi-module Gradle project
2) In the root project, assign the rootProject some extension property, e.g. rootProject.ext.foo = "BAR"
3) In sub-project, include gradle-docker-compose-plugin version 0.5.0, along with YAML file
4) Add something like this as well:
```
dockerCompose {
    environment.put "FOO_SETTING", rootProject.ext.foo
}
```
5) Confirm `composeUp` works
6) Now upgrade to gradle-docker-compose-plugin version 0.8.4
7) Repeat step (5)
EXPECTED RESULT: It still works
ACTUAL RESULT: Fails with error "'rootProject' is not property nor nested settings name"

Full stack is:
```
Caused by: groovy.lang.MissingPropertyException: 'rootProject' is not property nor nested settings name
        at com.avast.gradle.dockercompose.ComposeExtension.propertyMissing(ComposeExtension.groovy:22)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:251)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.ConfigureDelegate.getProperty(ConfigureDelegate.java:112)
        at build_agklknjyxucdialan8c05176u$_run_closure3.doCall(/work/project/subproject/build.gradle:17)
```

Note this might possibly have the same root cause as #164. The reproduce steps are different, but the errors are similar.

**Comment by skissane** [comment]
This still works if I upgrade from 0.5.0 to 0.5.9.
It also works upgrading from 0.5.0 to 0.6.0.
But upgrading to 0.6.1, it breaks.
