### ISSUE TITLE
captureContainersOutputToFiles does not capture output same as 'docker logs -f'

### ISSUE THREAD

**Issue by yunj** [avast/gradle-docker-compose-plugin#196]
**build.gradle**
```
dockerCompose {
  useComposeFiles = ['docker/docker-compose.yml']
  captureContainersOutputToFiles = 'build/test'
}
```

**docker-compose.yml**
```
version: '2'
services:
  web:
    build: ./ui
  wiremock:
    build: ./wiremock
```

I'm using the plugin version 0.9.4 and gradle 4.6. After running `docker-compose up`, it generates log files under the test folder for each service, i.e., web.log and wiremock.log.

Also, some error message appears together with BUILD SUCCESSFUL.
```
Will use localhost as host of web
Will use localhost as host of wiremock
Probing TCP socket on localhost:3030 of service 'web_1'
TCP socket on localhost:3030 of service 'web_1' is ready
Probing TCP socket on localhost:7070 of service 'wiremock_1'
TCP socket on localhost:7070 of service 'wiremock_1' is ready


BUILD SUCCESSFUL in 11s
1 actionable task: 1 executed
Exception in thread "pool-1-thread-1" org.gradle.internal.UncheckedException: java.lang.InterruptedException
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:298)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:34)
        at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:189)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1087)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1082)
        at org.gradle.api.Project$exec$2.call(Unknown Source)
        at com.avast.gradle.dockercompose.ComposeExecutor.executeWithCustomOutput(ComposeExecutor.groovy:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:82)
        at com.avast.gradle.dockercompose.ComposeExecutor.this$dist$invoke$1(ComposeExecutor.groovy)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.methodMissing(ComposeExecutor.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:939)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1262)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.run(ComposeExecutor.groovy:110)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:295)
        ... 30 more
Exception in thread "pool-2-thread-1" org.gradle.internal.UncheckedException: java.lang.InterruptedException
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:298)
        at org.gradle.process.internal.DefaultExecAction.e
```

After that, a few tests run against wiremock, which will trigger wiremock to generate log. I can see the newly generated log if I run `docker logs -f <container_id>`, however, I cannot see new log is appended to `wiremock.log`.

Please advise. Thanks.

**Comment by augi** [comment]
Hello and thank you for reporting!

The problem lies probably [in this code](https://github.com/avast/gradle-docker-compose-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/ComposeExecutor.groovy#L89) - the plugin executes a new process to capture the log outputs, and the output is redirected using Java code that runs in a background thread.

The exception you showed says that this thread was interrupted, and so redirecting of containers outputs to the files doesn't continue.

Possible solution could be to execute the process with an automatic redirecting to a file, like using `... >> web.log`. But then we would have to ensure this redirecting hadn't be done twice (or more times), e.g. store PID to a file and kill the process when executing the command again (tricky). We should also ensure that the child processes was detached from the parent process (because it's possible that Gradle's JVM ends).

Suggestion of any reliable solution is welcome!

**Comment by rvbabilonia** [comment]
Hi Michal,

Turns out this is similar to issue #207 that I raised. I disabled `captureContainersOutput` for now. While I don't see the startup logs being displayed apart from the TCP probe logs, at least I'm not getting the InterruptedException.

Cheers and more power!

**Comment by augi** [comment]
Closing due to recent inactivity.
