### ISSUE TITLE
Intellij + Spring Boot + bootRun + this plugin - composeDown fails

### ISSUE THREAD

**Issue by ben-lei-gfm** [avast/gradle-docker-compose-plugin#199]
Here's what I have in my gradle file:
```
dockerCompose.isRequiredBy(bootRun)
```

Starting up the containers via IntelliJ's "bootRun" task is fine, but when I try to stop it by pressing down stop button, I get something like this (+ it says bootRun failed):

```
> Task :bootRun FAILED

> Task :composeDown
failed to abort command '/usr/local/bin/docker-compose'
java.lang.IllegalStateException: Cannot abort process 'command '/usr/local/bin/docker-compose'' because it is not in started or detached state
	at org.gradle.process.internal.DefaultExecHandle.abort(DefaultExecHandle.java:287)
	at org.gradle.process.internal.ExecHandleShutdownHookAction.run(ExecHandleShutdownHookAction.java:39)
	at org.gradle.initialization.DefaultBuildCancellationToken.addCallback(DefaultBuildCancellationToken.java:46)
	at org.gradle.process.internal.DefaultExecHandle.started(DefaultExecHandle.java:334)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:72)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
failed to abort command '/usr/local/bin/docker-compose'
java.lang.IllegalStateException: Cannot abort process 'command '/usr/local/bin/docker-compose'' because it is not in started or detached state
	at org.gradle.process.internal.DefaultExecHandle.abort(DefaultExecHandle.java:287)
	at org.gradle.process.internal.ExecHandleShutdownHookAction.run(ExecHandleShutdownHookAction.java:39)
	at org.gradle.initialization.DefaultBuildCancellationToken.addCallback(DefaultBuildCancellationToken.java:46)
	at org.gradle.process.internal.DefaultExecHandle.started(DefaultExecHandle.java:334)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:72)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Stopping 7849c819be255b40433074fb1847a4a6_my__db_1 ... 
Stopping 7849c819be255b40433074fb1847a4a6_my__db_1 ... done

> Task :composeDown FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':bootRun'.
> Process 'command '/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java'' finished with non-zero exit value 143

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':composeDown'.
> Build cancelled during executing task ':composeDown'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 48s
5 actionable tasks: 4 executed, 1 up-to-date
1:32:50 PM: Task execution finished 'bootRun'.
```

I don't get this issue when I run ./gradlew bootRun + CTRL+C... but I do get a return status code of 130:

```
> :bootRun
^C                                                                                          
$ echo $?
130
```

**Comment by augi** [comment]
Hello, thank you for reporting this issue!

Actually, I don't know if it's even possible to handle this issue (see [this related](https://discuss.gradle.org/t/run-finalizedby-when-task-is-interrupted-ctrl-c-continued-from-old-forum/12036)). The point is that `finalizedBy` is not handled correctly when the build is aborted.

My recommendation is to have just `bootRun.dependsOn composeUp`, and when you don't need the running Docker Compose containers, then you can execute `composeDown` or `composeDownForced` task.

Feel free to open this issue if you think there is a Gradle API that could solve it.
