### ISSUE TITLE
InterruptedException on with composeUp composeDown

### ISSUE THREAD

**Issue by bellini-ea** [avast/gradle-docker-compose-plugin#218]
Hello,

I noticed that only when running the composeUp, composeDown, the build succeeds but there is a gradle interrupted exception.  It only happens with these commands it seems so posting here to see what you think.  Sorry, I've been keeping you busy these days :)

```
Exception in thread "pool-1-thread-1" org.gradle.internal.UncheckedException: java.lang.InterruptedException
BUILD SUCCESSFUL in 1m 42s
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:67)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:312)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:36)
        at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:145)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1117)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1112)
        at org.gradle.api.Project$exec$4.call(Unknown Source)
        at com.avast.gradle.dockercompose.ComposeExecutor.executeWithCustomOutput(ComposeExecutor.groovy:32)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
3 actionable tasks: 3 executed
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:96)
        at com.avast.gradle.dockercompose.ComposeExecutor.this$dist$invoke$1(ComposeExecutor.groovy)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.methodMissing(ComposeExecutor.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:958)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1286)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1219)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.run(ComposeExecutor.groovy:110)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2090)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:309)
        ... 29 more
Exception in thread "pool-3-thread-1" org.gradle.internal.UncheckedException: java.lang.InterruptedException
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:67)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:312)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:36)
        at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:145)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1117)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1112)
        at org.gradle.api.Project$exec$4.call(Unknown Source)
        at com.avast.gradle.dockercompose.ComposeExecutor.executeWithCustomOutput(ComposeExecutor.groovy:32)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:96)
        at com.avast.gradle.dockercompose.ComposeExecutor.this$dist$invoke$1(ComposeExecutor.groovy)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.methodMissing(ComposeExecutor.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:958)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1286)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1219)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.run(ComposeExecutor.groovy:110)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2090)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:309)
        ... 27 more
Exception in thread "pool-2-thread-1" org.gradle.internal.UncheckedException: java.lang.InterruptedException
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:67)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:312)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:36)
        at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:145)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1117)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1112)
        at org.gradle.api.Project$exec$4.call(Unknown Source)
        at com.avast.gradle.dockercompose.ComposeExecutor.executeWithCustomOutput(ComposeExecutor.groovy:32)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:96)
        at com.avast.gradle.dockercompose.ComposeExecutor.this$dist$invoke$1(ComposeExecutor.groovy)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.methodMissing(ComposeExecutor.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:958)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1286)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1219)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.run(ComposeExecutor.groovy:110)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2090)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:309)
        ... 27 more
```

**Comment by augi** [comment]
Thanks for reporting this! The background threads are expected to be interrupted so we will ignore this kind of exceptions there. The fix will be released soon.
