### ISSUE TITLE
composeUp causing InterruptedException at end of a gradle build

### ISSUE THREAD

**Issue by bellini-ea** [avast/gradle-docker-compose-plugin#220]
Hi,

I thought this one was fixed but I'm seeing this after doing and composeUp on any project I have.  It always appears at the end of a build whether its successful or failed.  Putting the entire stack here, sorry, its long

```
Exception in thread "pool-3-thread-1" org.gradle.internal.UncheckedException: java.lang.InterruptedException
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:67)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:312)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:36)
        at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:145)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1117)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1112)
        at org.gradle.api.Project$exec$4.call(Unknown Source)
        at com.avast.gradle.dockercompose.ComposeExecutor.executeWithCustomOutput(ComposeExecutor.groovy:32)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:96)
        at com.avast.gradle.dockercompose.ComposeExecutor.this$dist$invoke$1(ComposeExecutor.groovy)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.methodMissing(ComposeExecutor.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
BUILD SUCCESSFUL in 7m 43s
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:958)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1286)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1219)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.run(ComposeExecutor.groovy:110)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2090)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:309)
        ... 29 more
Exception in thread "pool-4-thread-1" org.gradle.internal.UncheckedException: java.lang.InterruptedException
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:67)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:312)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:36)
57 actionable tasks: 57 executed
        at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:145)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1117)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1112)
        at org.gradle.api.Project$exec$4.call(Unknown Source)
        at com.avast.gradle.dockercompose.ComposeExecutor.executeWithCustomOutput(ComposeExecutor.groovy:32)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:96)
        at com.avast.gradle.dockercompose.ComposeExecutor.this$dist$invoke$1(ComposeExecutor.groovy)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.methodMissing(ComposeExecutor.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:958)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1286)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1219)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.run(ComposeExecutor.groovy:110)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2090)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:309)
        ... 27 more
Exception in thread "pool-5-thread-1" org.gradle.internal.UncheckedException: java.lang.InterruptedException
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:67)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:312)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:36)
        at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:145)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1117)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1112)
        at org.gradle.api.Project$exec$4.call(Unknown Source)
        at com.avast.gradle.dockercompose.ComposeExecutor.executeWithCustomOutput(ComposeExecutor.groovy:32)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:96)
        at com.avast.gradle.dockercompose.ComposeExecutor.this$dist$invoke$1(ComposeExecutor.groovy)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.methodMissing(ComposeExecutor.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:958)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1286)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1219)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.run(ComposeExecutor.groovy:110)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2090)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:309)
        ... 27 more
Exception in thread "pool-6-thread-1" org.gradle.internal.UncheckedException: java.lang.InterruptedException
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:67)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:312)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:36)
        at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:145)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1117)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1112)
        at org.gradle.api.Project$exec$4.call(Unknown Source)
        at com.avast.gradle.dockercompose.ComposeExecutor.executeWithCustomOutput(ComposeExecutor.groovy:32)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:96)
        at com.avast.gradle.dockercompose.ComposeExecutor.this$dist$invoke$1(ComposeExecutor.groovy)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.methodMissing(ComposeExecutor.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:958)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1286)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1219)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.run(ComposeExecutor.groovy:110)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2090)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:309)
        ... 27 more
Exception in thread "pool-7-thread-1" org.gradle.internal.UncheckedException: java.lang.InterruptedException
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:67)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:312)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:36)
        at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:145)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1117)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1112)
        at org.gradle.api.Project$exec$4.call(Unknown Source)
        at com.avast.gradle.dockercompose.ComposeExecutor.executeWithCustomOutput(ComposeExecutor.groovy:32)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:96)
        at com.avast.gradle.dockercompose.ComposeExecutor.this$dist$invoke$1(ComposeExecutor.groovy)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.methodMissing(ComposeExecutor.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:958)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1286)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1219)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at com.avast.gradle.dockercompose.ComposeExecutor$1.run(ComposeExecutor.groovy:110)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2090)
        at org.gradle.process.internal.DefaultExecHandle.waitForFinish(DefaultExecHandle.java:309)
```

**Comment by augi** [comment]
Hello, thanks for your report! Which version of plugin and Gradle are you using, please?

It looks like Gradle < 5.0 _incorrectly_ wrapped `InterruptedException` to an `UncheckedException`. This was fixed [with this commit](https://github.com/gradle/gradle/commit/506aa2182392c562c2a0a61e4ad44ccbf8888ff0#diff-8a74d9e0bccb86e408d02ba22fe8c745).

As we are declaring `4.9` as minimal required version, we are going to handle this situation ASAP.

**Comment by bellini-ea** [comment]
This is with version 5.6.4 of Gradle and the latest version of this plugin.

**Comment by bellini-ea** [comment]
I upgrade to 0.10.9 and its fixed!  Thank you.
