### ISSUE TITLE
composeBuild Failing with Python Stack

### ISSUE THREAD

**Issue by bellini-ea** [avast/gradle-docker-compose-plugin#273]
I have a new project that I'm applying this plugin to.  I do have this plugin successfully working in two other projects but am running into the following issue with this new project.   Any thoughts are appreciated.

task: composeBuild but also happens with composeUp
Gradle: 6.6.1 with Kotlin DSL
Plugin version: 0.13.4
Plugin configuration:
```
	dockerCompose {
		projectName = dockerGroupName 
		useComposeFiles = listOf("./docker/docker-compose.yml")
		removeOrphans = false                                                   
		captureContainersOutput = true                                     
		captureContainersOutputToFile = project.file("$buildDir/docker/containerlog.txt") 
		captureContainersOutputToFiles = project.file("$buildDir/docker/")      
		composeLogToFile = project.file("$buildDir/docker/composeUpDownlog.txt")
		containerLogToDir = project.file("$buildDir/docker/containerlog.txt")
		buildAdditionalArgs = listOf("--build-arg", "ENV_NAME=local")
	}
```
If I run the comment that the plugin prints out, it builds fine.  For example `docker-compose --no-ansi -f ./docker/docker-compose.yml -p poutine-docker build --build-arg ENV_NAME=local` will build fine but `gradlew composeBuild` fails the following:

```
2020-11-17T17:09:29.538-0800 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command 'docker-compose''. Working directory: C:\dev\projects\remz Command: docker-compose --no-ansi -f ./docker/docker-compose.yml -p poutine-docker build --build-arg ENV_NAME=local
2020-11-17T17:09:29.540-0800 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
2020-11-17T17:09:29.541-0800 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'docker-compose'.
2020-11-17T17:09:29.550-0800 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
2020-11-17T17:09:29.550-0800 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
2020-11-17T17:09:29.550-0800 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command 'docker-compose''
2020-11-17T17:09:30.468-0800 [ERROR] [system.err] The AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
2020-11-17T17:09:30.468-0800 [ERROR] [system.err] The AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
2020-11-17T17:09:30.776-0800 [ERROR] [system.err] jaeger uses an image, skipping
2020-11-17T17:09:30.776-0800 [ERROR] [system.err] Building remz
2020-11-17T17:09:30.878-0800 [ERROR] [system.err] Traceback (most recent call last):
2020-11-17T17:09:30.879-0800 [ERROR] [system.err]   File "c:\python38\lib\site-packages\docker\utils\build.py", line 97, in create_archive
2020-11-17T17:09:30.879-0800 [ERROR] [system.err]     t.addfile(i, f)
2020-11-17T17:09:30.879-0800 [ERROR] [system.err]   File "c:\python38\lib\tarfile.py", line 1995, in addfile
2020-11-17T17:09:30.879-0800 [ERROR] [system.err]     copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
2020-11-17T17:09:30.879-0800 [ERROR] [system.err]   File "c:\python38\lib\tarfile.py", line 253, in copyfileobj
2020-11-17T17:09:30.879-0800 [ERROR] [system.err]     buf = src.read(remainder)
2020-11-17T17:09:30.879-0800 [ERROR] [system.err] PermissionError: [Errno 13] Permission denied
2020-11-17T17:09:30.880-0800 [ERROR] [system.err]
2020-11-17T17:09:30.880-0800 [ERROR] [system.err] During handling of the above exception, another exception occurred:
2020-11-17T17:09:30.880-0800 [ERROR] [system.err]
2020-11-17T17:09:30.880-0800 [ERROR] [system.err] Traceback (most recent call last):
2020-11-17T17:09:30.880-0800 [ERROR] [system.err]   File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
2020-11-17T17:09:30.880-0800 [ERROR] [system.err]     return _run_code(code, main_globals, None,
2020-11-17T17:09:30.881-0800 [ERROR] [system.err]   File "c:\python38\lib\runpy.py", line 87, in _run_code
2020-11-17T17:09:30.881-0800 [ERROR] [system.err]     exec(code, run_globals)
2020-11-17T17:09:30.881-0800 [ERROR] [system.err]   File "C:\Python38\Scripts\docker-compose.exe\__main__.py", line 9, in <module>
2020-11-17T17:09:30.881-0800 [ERROR] [system.err]   File "c:\python38\lib\site-packages\compose\cli\main.py", line 72, in main
2020-11-17T17:09:30.881-0800 [ERROR] [system.err]     command()
2020-11-17T17:09:30.881-0800 [ERROR] [system.err]   File "c:\python38\lib\site-packages\compose\cli\main.py", line 128, in perform_command
2020-11-17T17:09:30.881-0800 [ERROR] [system.err]     handler(command, command_options)
2020-11-17T17:09:30.882-0800 [ERROR] [system.err]   File "c:\python38\lib\site-packages\compose\cli\main.py", line 292, in build
2020-11-17T17:09:30.882-0800 [ERROR] [system.err]     self.project.build(
2020-11-17T17:09:30.882-0800 [ERROR] [system.err]   File "c:\python38\lib\site-packages\compose\project.py", line 403, in build
2020-11-17T17:09:30.882-0800 [ERROR] [system.err]     build_service(service)
2020-11-17T17:09:30.882-0800 [ERROR] [system.err]   File "c:\python38\lib\site-packages\compose\project.py", line 385, in build_service
2020-11-17T17:09:30.882-0800 [ERROR] [system.err]     service.build(no_cache, pull, force_rm, memory, build_args, gzip, rm, silent, cli, progress)
2020-11-17T17:09:30.882-0800 [ERROR] [system.err]   File "c:\python38\lib\site-packages\compose\service.py", line 1086, in build
2020-11-17T17:09:30.882-0800 [ERROR] [system.err]     build_output = builder.build(
2020-11-17T17:09:30.883-0800 [ERROR] [system.err]   File "c:\python38\lib\site-packages\docker\api\build.py", line 159, in build
2020-11-17T17:09:30.883-0800 [ERROR] [system.err]     context = utils.tar(
2020-11-17T17:09:30.883-0800 [ERROR] [system.err]   File "c:\python38\lib\site-packages\docker\utils\build.py", line 29, in tar
2020-11-17T17:09:30.883-0800 [ERROR] [system.err]     return create_archive(
2020-11-17T17:09:30.883-0800 [ERROR] [system.err]   File "c:\python38\lib\site-packages\docker\utils\build.py", line 99, in create_archive
2020-11-17T17:09:30.883-0800 [ERROR] [system.err]     raise IOError(
2020-11-17T17:09:30.883-0800 [ERROR] [system.err] OSError: Can not read file in context: \\?\C:\dev\gitlab.ea\poutine\remz\.gradle\6.6.1\executionHistory\executionHistory.lock
2020-11-17T17:09:30.969-0800 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
2020-11-17T17:09:30.969-0800 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'docker-compose'' finished with exit value 1 (state: FAILED)

**Comment by augi** [comment]
Hello, it looks like some environment variables are missing. You could debug it if you replaced containers' entrypoint with `getenv` command (or similar).

**Comment by bellini-ea** [comment]
The missing environment variables don't cause an issues.  Removing them results in the same issue. 

PermissionError: [Errno 13] Permission denied seems to be the issue but I cannot see what file.

**Comment by augi** [comment]
OK, the file is a Gradle internal file so I guess your containers shouldn't need it. So just ensure this file (or better, whole `.gradle` directory) is not in Docker build context, so use `.dockerignore` file.

**Comment by bellini-ea** [comment]
.gradle was ending up in the context...interesting... adding .dockerignore did fix it.  Thanks so much!  (only happens on windows as well).
