### ISSUE TITLE
composeUp prematurely fails for apps with restart policy that do eventually run

### ISSUE THREAD

**Issue by simontankersley** [avast/gradle-docker-compose-plugin#274]
We have a setup where we are using the [restart policy](https://docs.docker.com/compose/reference/restart/) in docker-compose.

When running composeUp the waiting for the tcp port usually fail prematurely (before the 15 minute timeout) for a couple of reasons:

1. When checkContainersRunning is set to false, the composeUp task halts because of an java.lang.UnsupportedOperationException
2. When checkContainersRunning is set to true, the composeUp task halts if the container is in the "restarting" state

You can see 1 by cloning https://github.com/simontankersley/gradle-docker-compose-issue-demo-1 and running:

`./gradlew composeUp --debug --stacktrace`

Note that this is just a demonstration as in reality there should be an application that binds to the 8080 port. It isn't needed to demonstrate the problem however as the task fails before the default 15 minute tcp port check timeout.

You should see output like:

```
...
2020-12-17T16:18:26.379+1300 [LIFECYCLE] [org.gradle.api.Task] Going to replace container information of 'example_1' because port 8080 was exposed as 8080 but is null now
2020-12-17T16:18:26.379+1300 [DEBUG] [org.gradle.api.Task] Failed to start-up Docker containers
java.lang.UnsupportedOperationException
        at java.base/java.util.Collections$UnmodifiableMap.replace(Collections.java:1546)
        at java_util_Map$replace$3.call(Unknown Source)
        at com.avast.gradle.dockercompose.tasks.ComposeUp$_waitForOpenTcpPorts_closure14$_closure25$_closure27.doCall(ComposeUp.groovy:250)
...
 ```
 
This exits before the default 15 minute tcp check timeout

You can see 2 by cloning https://github.com/simontankersley/gradle-docker-compose-issue-demo-2 and running:

`./gradlew composeUp --debug --stacktrace`

Note that this is just a demonstration as in reality there should be an application that binds to the 8080 port. It isn't needed to demonstrate the problem however as the task fails before the default 15 minute tcp port check timeout.

You should see output like:

```
...
2020-12-17T16:21:46.210+1300 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: SUCCEEDED
2020-12-17T16:21:46.211+1300 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command '/usr/local/bin/docker'' finished with exit value 0 (state: SUCCEEDED)
2020-12-17T16:21:46.212+1300 [DEBUG] [org.gradle.api.Task] Failed to start-up Docker containers
java.lang.RuntimeException: Container 70d5a34692408aea1f6370becd3c6c9869b1f47c8c4c3369b6fb36dbea551b19 of example_1 is not running. Logs:
...
```

This exits before the default 15 minute tcp check timeout

It would be good if the composeUp task can take into account the "restarting" state of a container and perhaps loop back around to recheck the tcp port instead of failing. In my case the application will eventually start

**Comment by augi** [comment]
Hello, thank you very much for your report!

Regarding the `java.lang.UnsupportedOperationException` exception - it is really bug. I wasn't aware that Groovy automatically converts collections assigning to `@Immutable` classes to unmodifiable collections. 

Also, you are right that we should check for both `running` and `restarting` container's states so I will address this issue ASAP as well.
