### ISSUE TITLE
'ComposeUp' Does not work on the Apple silicon.

### ISSUE THREAD

**Issue by LeeKyoungIl** [avast/gradle-docker-compose-plugin#320]
Hello.  (I am using it well. thank you.)

I'm trying to use plugin on my the Apple silicon macbook. 
I use the latest version of the docker for desktop for Apple silicon. 

But not work. 

this is error log. 

```
2021-08-29T23:23:53.095+0900 [ERROR] [system.err] exec: "docker-compose-v1": executable file not found in $PATH
2021-08-29T23:23:53.096+0900 [ERROR] [system.err] Current PATH : /usr/bin:/bin:/usr/sbin:/sbin
2021-08-29T23:23:53.100+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2021-08-29T23:23:53.100+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
2021-08-29T23:23:53.100+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2021-08-29T23:23:53.100+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
2021-08-29T23:23:53.100+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':mercury-externals:local-gateway:composeUp'.
2021-08-29T23:23:53.100+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Exit-code 1 when calling /usr/local/bin/docker-compose, stdout: 
```

In this log said, the docker-compose-v1 executable file not found in $PATH
But my enviroment is no problem, anywhere all of docker command is working in my mac.

And this is part of info log made by the plugin.

```
 /usr/local/bin/docker-compose -f ./docker-nginx/docker-compose.yml -p fe58e6c7cd2a24ffa7da4cfc49c27bac_local-gateway_ version --short
```

I use this option

```
buildBeforeUp = true
```

But there is no 'up' command in '**made by the plugin.**'

In my opinion 'up' should be include the command.

How can I fix that?

**Comment by augi** [comment]
Hello,

the plugin performs something like `docker-compose version --short` at the start, to get the version of Docker Compose installed. And it fails even on this command, so `docker-compose up` is not invoked.

Unfortunately, I don't have any experience with _Apple silicon macbook` so I'm not able to get you a straight answer.

By default, the path to `docker-compose` binary is set to `/usr/local/bin/docker-compose` on MacOS, see [this code](https://github.com/avast/gradle-docker-compose-plugin/blob/main/src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy#L162). You can customize this value by setting `executable` settings. Actually, it looks like you already set this setting to `docker-compose-v1` value, and this is why it doesn't work. I don't have a better explanation now as there isn't any occurrence of `docker-compose-v1` string in this plugin codebase 🤔

**Comment by IntrepidDemian** [comment]
I too am seeing this issue with my grails project on my new MacBook Pro M1X Max. I will take the information provided in here so far and see if I can make any progress on a work-around. Just wanted to drop a comment on this ticket that has been around for a bit so it is know that there is still interest in solving this issue.

**Comment by robevansuk** [comment]
Can confirm - MBP M1X Pro using v 0.10.10

```
Error during callback
java.io.IOException: Couldn't load native library
	at org.newsclub.net.unix.AFUNIXSocket.setIsCreated(AFUNIXSocket.java:56)
	at org.newsclub.net.unix.AFUNIXSocket.<init>(AFUNIXSocket.java:48)
	at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:77)
	at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:72)
	at com.github.dockerjava.jaxrs.ApacheUnixSocket.<init>(ApacheUnixSocket.java:52)
	at com.github.dockerjava.jaxrs.UnixConnectionSocketFactory.createSocket(UnixConnectionSocketFactory.java:67)
	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:119)
	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
...
```

When I update gradle from 5.1 -> 6.1 to the stack trace points to the same error:

```
Caused by: java.io.IOException: Couldn't load native library
	at org.newsclub.net.unix.AFUNIXSocket.setIsCreated(AFUNIXSocket.java:56)
	at org.newsclub.net.unix.AFUNIXSocket.<init>(AFUNIXSocket.java:48)
	at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:77)
	at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:72)
	at com.github.dockerjava.jaxrs.ApacheUnixSocket.<init>(ApacheUnixSocket.java:52)
	at com.github.dockerjava.jaxrs.UnixConnectionSocketFactory.createSocket(UnixConnectionSocketFactory.java:67)
	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:119)
	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at com.bmuschko.gradle.docker.shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
```

**Comment by augi** [comment]
@robevansuk Hello, according to the stacktrace provided, you are using a different Gradle plugin.

**Comment by robevansuk** [comment]
@augi Thanks for the response, I realised shortly after posting. Unfortunately the images I'm working with are incompatible as well as the plugin being incompatible as the images are built for `--platform linux/amd64` and not `--platform linux/arm/v8` or `--platform linux/arm64` - I got hold of some (but not all) corresponding images, however there's still too much of a discrepancy between the two platforms to make all the images I require work together. Spent a few hours looking and made some progress, unfortunately the new mac's with the arm64 introduce such a massive breaking change I'm not sure I'll be able to use it for work any time soon. I did bump my version of Gradle and the version of the avast plugin for building images and that bit seemed to be ok though :)

**Comment by dzharikhin** [comment]
Is there something I can help to fix the issue? It is very annoying to call compose up manually each time)

It seems like docker-compose binary itself is running from the plugin with bad PATH env which leads to the error
but docker-compose command is definitely working fine if running by hand
So, it seems fix is somewhere around propagating environment to execution of docker-compose, but I'm not sure where it should be done

**Comment by augi** [comment]
I don't have MacOS so I cannot work on this, sorry.

* The environment of the `docker-compose` command execution is here: https://github.com/avast/gradle-docker-compose-plugin/blob/main/src/main/groovy/com/avast/gradle/dockercompose/ComposeExecutor.groovy#L49
* The default value is just copied from the parent process (~Gradle process): https://github.com/avast/gradle-docker-compose-plugin/blob/main/src/main/groovy/com/avast/gradle/dockercompose/ComposeSettings.groovy#L171

**Comment by dzharikhin** [comment]
I've tried:
1. Provide env in task 
```kotlin
 tasks.withType<Test> {
        environment("PATH", "${System.getenv()["PATH"]}:/usr/local/bin")
        dockerCompose.isRequiredBy(this@withType)
        ...
}
```
2. Run gradle with env 
`PATH=$PATH:/usr/local/bin ./gradlew build`
no result, but today I tried to update to the latest gradle 7.x and it worked!)))
So FYI

**Comment by augi** [comment]
So just plain update to Gradle 7 solved this issue for you? 🤔

**Comment by dzharikhin** [comment]
Well, looks like it. Latest docker + gradle 7.x  
So, now I'm thinking root cause cause was somewhere in gradle's exec spi even more. Nothing to do with the plugin itself

**Comment by augi** [comment]
Cool, thank you for reporting this! Yes, it looks like it could be a problem with the exec API of Gradle itself.
