### ISSUE TITLE
0.17.5 does not work with docker-compose 2.21.0

### ISSUE THREAD

**Issue by flozano** [avast/gradle-docker-compose-plugin#424]
```
> Task :composeUp FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':composeUp'.
> docker-compose version 0.0.0 doesn't support --scale option
```

relevant parts of stack-trace:
```
Caused by: java.lang.UnsupportedOperationException: docker-compose version 0.0.0 doesn't support --scale option
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.gradle.internal.classpath.intercept.CallInterceptorsSet$DecoratingCallSite.access$401(CallInterceptorsSet.java:128)
        at org.gradle.internal.classpath.intercept.CallInterceptorsSet$DecoratingCallSite$4.callOriginal(CallInterceptorsSet.java:180)
        at org.gradle.internal.classpath.intercept.CallInterceptorsSet$1.doIntercept(CallInterceptorsSet.java:54)
        at org.gradle.internal.classpath.intercept.CallInterceptorsSet$DecoratingCallSite.callConstructor(CallInterceptorsSet.java:177)
        at com.avast.gradle.dockercompose.ComposeExecutor.isScaleSupported(ComposeExecutor.groovy:274)
        at com.avast.gradle.dockercompose.ComposeExecutor$isScaleSupported$0.call(Unknown Source)
        at com.avast.gradle.dockercompose.tasks.ComposeUp.up(ComposeUp.groovy:129)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   
```

**Comment by flozano** [comment]
with 2.18.1:
```
$ docker-compose --version --short
2.18.1
```

with 2.21.0:
```
docker-compose --version --short
2.21.0-desktop.1
```
the trailing `desktop.1` is probably causing the issue?

**Comment by augi** [comment]
Hi, thank you for the report. Check [this commit](https://github.com/avast/gradle-docker-compose-plugin/commit/1615aeeb3a0d931aef9408c183c0ea7050bccd3f) that should solve this issue, also with test case covering this value.

**Comment by augi** [comment]
I'm checking your stacktrace and don't have any explanation why this is happening 😢 Maybe could you also try to execute `docker compose version --short`?

**Comment by flozano** [comment]
```
$ docker compose version --short
2.21.0-desktop.1
```

We tried installing discrete docker-compose with brew, in order to fix, and it has different output:
```
$ docker-compose version --short
2.22.0
```
